### PR TITLE
Feature -> password attribute in UserDetails

### PR DESCRIPTION
**Pull request by theSuiGenerisAakash**
Please run the tests and review. 

P.S. We would be able to successfully close the coverage issue if this works out in the `development` branch post-merge.

### CODE REVIEW

**Comment by theSuiGenerisAakash** [comment]
#23

**Review by sahilbalodi — APPROVED** [review]
approved , merge it

**Review by maheshhp — APPROVED** [review]
Need some clarity on password string length being stored and the type of encryption being used. Can be discussed during next meeting.

**Comment by theSuiGenerisAakash** [comment]
@maheshhp For the type of encryption talk, we have #8 . It's mostly going to be using bscryptjs. String length is a nice idea though.

**Pull request merged**
