### PR TITLE
Feature admin inventory fixed conflicts

### PR DESCRIPTION
**Pull request by ananddeb23**
This is Mahesh's branch modified. It had conflicts after Aakash's branch was merged with the development branch. Please review it. Did not commit and push changes to Mahesh's branch in case there was some mistake I was making which could corrupt the main branch.

With this branch.

1. Add product by id works (even for duplicate hits)
2. Add product by description/ bulk add product works (even for duplicate hits)
3. Remove product by id works. (with appropriate messages if product has been removed/not in DB)
4. product view by id works (for product id's in the DB)
5. Product view by category works too( not sure)
6. npm start has src/server.js change in package.json( This was a conflict too).

Once approved this can be safely merged with development branch. Please test it.
Front end integrated and is working.

In case this branch does not solve the issue, feel free to delete it.

### CODE REVIEW

**Review by theSuiGenerisAakash — COMMENTED** [review]
I understand both of our branches - Mahe's and mine. Nice idea to have done it as an experiment on a temporary branch. I will initiate the merge of Mahesh's branch tomorrow after I'm done with the exams. The merge conflict resolution there can be retested by you guys.

**Comment by ananddeb23** [comment]
This branch has already resolved the conflicts. I would suggest you try this one out first to save time. You might end up doing the same task twice otherwise.

**Comment by theSuiGenerisAakash** [comment]
I understand that, Anand. But doesn't it look a little over and unnatural to have a branch to just resolve conflicts? I mean, if there wasn't any way to resolve conflicts on the branch to-be-merged, I would have gone ahead here but it's just the usual case of merge conflict resolution that we've encountered. I had already resolved the conflicts through command line.. I just need to push and merge. What do you say?
I have taken into consideration everything that you've done here.

**Comment by sahilbalodi** [comment]
We don't have time .....anand has already resolved conflicts ....we can merge it so that we can continue with our work and not wait for tomorrow

**Comment by theSuiGenerisAakash** [comment]
Tests are failing. Please wait while I enquire.

**Comment by maheshhp** [comment]
Conflicts have been resolved in the development branch itself

**Pull request closed without merging**
