### PR TITLE
Create route user registration

### PR DESCRIPTION
**Pull request by sahilbalodi**

### CODE REVIEW

**Review by ananddeb23 — APPROVED** [review]
Nice work with validations. Some tests like password hash I feel were not needed as done but nice of you to have tested so meticulously! Also, the test descriptions of first few tests might be made a bit easier to comprehend with a little more of description.

**Comment by theSuiGenerisAakash** [comment]
Please run `git rm --cached -r coverage` to remove all the coverage files to avoid merge commits for others who would want to work on similar files and tests. Uske baad commit kar.

**Review by theSuiGenerisAakash — APPROVED** [review]
Looks good.

**Review by maheshhp — APPROVED** [review]
It can be merged

**Pull request merged**
