### PR TITLE
Orders - Migrations and Models

### PR DESCRIPTION
**Pull request by theSuiGenerisAakash**
Referencing this issue #12 , OrderDetails migrations and models are working fine with tests passing.

### CODE REVIEW

**Review by sahilbalodi — APPROVED** [review]
approved , go ahead

**Comment by theSuiGenerisAakash** [comment]
Merge conflicts resolved. Peeps check your `.gitignore` and verify `coverage/`.

**Review by maheshhp — APPROVED** [review]
Tests passing. Repository still contains coverage directory. Is it normal?

**Comment by theSuiGenerisAakash** [comment]
@maheshhp That's because of both of us having the `.gitignore` wrong. Will take care of it in the next feature realease.

**Pull request merged**
