### PR TITLE
Added get product details by ID and Category feature

### PR DESCRIPTION
**Pull request by maheshhp**
The getProductById and getProductByCategory from local DB is complete

### CODE REVIEW

**Review by theSuiGenerisAakash — APPROVED** [review]

**Review by ananddeb23 — CHANGES_REQUESTED** [review]
In add products by id the message on hitting again for same id could be 'Product already added' instead of 'Product updated'  - Suggestion

Add products by category is not working properly.  Hitting from front end. Response : No product added.

Tried hitting the heroku app directly using request https://shop-social-product-api.herokuapp.com/products/?category.name=TVs&manufacturer[$like]=*Insignia`*&price[$gt]=160&price[$lt]=180

GOT response as {
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}
Atul suggested something might be wrong with the the heroku app logic

**Comment by maheshhp** [comment]
The message 'Products updated' appears because an upsert is being done when a product is to be added. This updates the existing details if any of them have changed.

Regarding the query to the heroku app, I have followed the example queries here: https://shop-social-product-api.herokuapp.com/queries

Please let me know if any changes have to be done to the query for fetching the details by category and price

**Comment by ananddeb23** [comment]
https://shop-social-product-api.herokuapp.com/products/?category.name=TVs&manufacturer[$like]=*Insignia`*&price[$gt]=160&price[$lt]=170

Hitting the above. response - 
{
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}

**Comment by theSuiGenerisAakash** [comment]
@ananddeb 23 You're hitting with the wrong  one. There's a tilde after Insignia which doesn't need to be there.

This is perfectly fine 
https://shop-social-product-api.herokuapp.com/products/?category.name=TVs&manufacturer%5B$like%5D=*Insignia*&price%5B$gt%5D=160&price%5B$lt%5D=170

**Comment by ananddeb23** [comment]
getProductsByCategoryAndPrice(JSON.parse(request.payload)).then((remoteFetchResponse) => {

**Comment by maheshhp** [comment]
@ananddeb23 I have fixed the JSON request issue. Please test it and review the same.

**Comment by theSuiGenerisAakash** [comment]
We should not use JSON.stringify. Why is the last commit made that way?

**Comment by maheshhp** [comment]
The branch has been updated with the current state of development branch and all the tests have been run. Tests are passing.
Please review it and merge it.

**Pull request merged**
